---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dockerbuilds.icekube.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Phase
    format: byte
    name: phase
    priority: 1
    type: string
  group: icekube.io
  names:
    kind: DockerBuild
    listKind: DockerBuildList
    plural: dockerbuilds
    singular: dockerbuild
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            docker:
              properties:
                contextPath:
                  description: Path relative to workspace directory
                  type: string
                dockerfilePath:
                  description: Path relative to workspace directory
                  type: string
                imageName:
                  type: string
                registry:
                  type: string
                tag:
                  type: string
                user:
                  type: string
              required:
              - user
              - imageName
              - tag
              - contextPath
              - dockerfilePath
              type: object
            dockerSecret:
              type: string
            volumeMounts:
              items:
                properties:
                  name:
                    type: string
                  path:
                    type: string
                  pvcName:
                    type: string
                  subPath:
                    type: string
                required:
                - name
                - pvcName
                type: object
              type: array
          required:
          - dockerSecret
          - docker
          - volumeMounts
          type: object
        status:
          properties:
            duration:
              format: int32
              type: integer
            finishedTime:
              format: date-time
              type: string
            initializedTime:
              format: date-time
              type: string
            pendingDuration:
              format: int32
              type: integer
            pendingStartedTime:
              format: date-time
              type: string
            phase:
              type: string
            podName:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
