apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitclones.icekube.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Phase
    format: byte
    name: phase
    type: string
  group: icekube.io
  names:
    kind: GitClone
    listKind: GitCloneList
    plural: gitclones
    singular: gitclone
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            getMetadata:
              type: boolean
            git:
              properties:
                auth:
                  properties:
                    secret:
                      type: string
                    type:
                      type: string
                  required:
                  - secret
                  - type
                  type: object
                commitSHA:
                  type: string
                repositoryURL:
                  type: string
              required:
              - commitSHA
              - repositoryURL
              type: object
            volume:
              properties:
                pvcName:
                  type: string
                subPath:
                  type: string
              required:
              - pvcName
              type: object
          required:
          - git
          - volume
          type: object
        status:
          properties:
            checkoutMetadata:
              properties:
                authorDate:
                  type: string
                authorEmail:
                  type: string
                authorName:
                  type: string
                commitHash:
                  type: string
                logHeader:
                  type: string
                logMessage:
                  type: string
                reflogEmail:
                  type: string
                reflogName:
                  type: string
              type: object
            duration:
              format: int32
              type: integer
            finishedTime:
              format: date-time
              type: string
            initializedTime:
              format: date-time
              type: string
            message:
              type: string
            phase:
              type: string
            podStatus:
              properties:
                exitCode:
                  description: Pod main container (at index 0) return code
                  format: int32
                  type: integer
                name:
                  description: Name of pod
                  type: string
              type: object
            reason:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
