---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backingservices.icekube.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Phase
    format: byte
    name: phase
    priority: 1
    type: string
  group: icekube.io
  names:
    kind: BackingService
    listKind: BackingServiceList
    plural: backingservices
    singular: backingservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            dockerSecret:
              properties:
                secretName:
                  description: Name of kubernetes secret
                  type: string
              required:
              - secretName
              type: object
            env:
              additionalProperties:
                type: string
              type: object
            hosts:
              additionalProperties:
                type: string
              type: object
            image:
              type: string
            imagePullSecret:
              type: string
            nodeSelector:
              additionalProperties:
                type: string
              type: object
            resourceRequest:
              properties:
                cpu:
                  type: string
                memory:
                  type: string
              type: object
            script:
              type: string
            serviceName:
              pattern: ^[a-z]+[a-z\-_0-9]+$
              type: string
          required:
          - image
          - serviceName
          type: object
        status:
          properties:
            duration:
              format: int32
              type: integer
            finishedTime:
              format: date-time
              type: string
            initializedTime:
              format: date-time
              type: string
            message:
              type: string
            pendingDuration:
              format: int32
              type: integer
            pendingStartedTime:
              format: date-time
              type: string
            phase:
              type: string
            podIP:
              type: string
            podStatus:
              properties:
                exitCode:
                  description: Pod main container (at index 0) return code
                  format: int32
                  type: integer
                name:
                  description: Name of pod
                  type: string
              type: object
            reason:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
